from BaseClasses import Item
from typing import NamedTuple, Dict, Optional


class ItemData(NamedTuple):
    code: Optional[int]
    progression: bool


item_table: Dict[str, ItemData] = {
    "Coin": ItemData(1, False),

    "Idea: Animal Pen": ItemData(1, True),
    "Idea: Aquarium": ItemData(1, True),
    "Idea: Axe": ItemData(1, True),
    "Idea: Blunderbuss": ItemData(1, True),
    "Idea: Bone Spear": ItemData(1, True),
    "Idea: Bone Staff": ItemData(1, True),
    "Idea: Boomerang": ItemData(1, True),
    "Idea: Bottle of Rum": ItemData(1, True),
    "Idea: Bow": ItemData(1, True),
    "Idea: Breeding Pen": ItemData(1, True),
    "Idea: Brick": ItemData(1, True),
    "Idea: Brickyard": ItemData(1, True),
    "Idea: Broken Bottle": ItemData(1, True),
    "Idea: Butchery": ItemData(1, True),
    "Idea: Campfire": ItemData(1, True),
    "Idea: Cathedral": ItemData(1, True),
    "Idea: Ceviche": ItemData(1, True),
    "Idea: Chainmail Armor": ItemData(1, True),
    "Idea: Charcoal": ItemData(1, True),
    "Idea: Chicken": ItemData(1, True),
    "Idea: Club": ItemData(1, True),
    "Idea: Coin Chest": ItemData(1, True),
    "Idea: Coin": ItemData(1, True),
    "Idea: Composter": ItemData(1, True),
    "Idea: Cooked Meat": ItemData(1, True),
    "Idea: Crane": ItemData(1, True),
    "Idea: Crossbow": ItemData(1, True),
    "Idea: Distillery": ItemData(1, True),
    "Idea: Dustbin": ItemData(1, True),
    "Idea: Empty Bottle": ItemData(1, True),
    "Idea: Fabric": ItemData(1, True),
    "Idea: Farm": ItemData(1, True),
    "Idea: Fish Trap": ItemData(1, True),
    "Idea: Fishing Rod": ItemData(1, True),
    "Idea: Forest Amulet": ItemData(1, True),
    "Idea: Frigate": ItemData(1, True),
    "Idea: Frittata": ItemData(1, True),
    "Idea: Fruit Salad": ItemData(1, True),
    "Idea: Garden": ItemData(1, True),
    "Idea: Glass": ItemData(1, True),
    "Idea: Gold Bar": ItemData(1, True),
    "Idea: Gold Mine": ItemData(1, True),
    "Idea: Golden Chestplate": ItemData(1, True),
    "Idea: Greenhouse": ItemData(1, True),
    "Idea: Growth": ItemData(1, True),
    "Idea: Hammer": ItemData(1, True),
    "Idea: Hotpot": ItemData(1, True),
    "Idea: House": ItemData(1, True),
    "Idea: Iron Bar": ItemData(1, True),
    "Idea: Iron Mine": ItemData(1, True),
    "Idea: Iron Shield": ItemData(1, True),
    "Idea: Lighthouse": ItemData(1, True),
    "Idea: Lumber Camp": ItemData(1, True),
    "Idea: Magic Blade": ItemData(1, True),
    "Idea: Magic Glue": ItemData(1, True),
    "Idea: Magic Ring": ItemData(1, True),
    "Idea: Magic Staff": ItemData(1, True),
    "Idea: Magic Tome": ItemData(1, True),
    "Idea: Magic Wand": ItemData(1, True),
    "Idea: Market": ItemData(1, True),
    "Idea: Mess Hall": ItemData(1, True),
    "Idea: Milkshake": ItemData(1, True),
    "Idea: Mountain Amulet": ItemData(1, True),
    "Idea: Offspring": ItemData(1, True),
    "Idea: Omelette": ItemData(1, True),
    "Idea: Pickaxe": ItemData(1, True),
    "Idea: Plank": ItemData(1, True),
    "Idea: Quarry": ItemData(1, True),
    "Idea: Resource Chest": ItemData(1, True),
    "Idea: Resource Magnet": ItemData(1, True),
    "Idea: Rope": ItemData(1, True),
    "Idea: Rowboat": ItemData(1, True),
    "Idea: Sacred Key": ItemData(1, True),
    "Idea: Sail": ItemData(1, True),
    "Idea: Sand Quarry": ItemData(1, True),
    "Idea: Sandstone": ItemData(1, True),
    "Idea: Sawmill": ItemData(1, True),
    "Idea: Seafood Stew": ItemData(1, True),
    "Idea: Shed": ItemData(1, True),
    "Idea: Shell Chest": ItemData(1, True),
    "Idea: Slingshot": ItemData(1, True),
    "Idea: Sloop": ItemData(1, True),
    "Idea: Smelter": ItemData(1, True),
    "Idea: Spear": ItemData(1, True),
    "Idea: Spiked Plank": ItemData(1, True),
    "Idea: Stable Portal": ItemData(1, True),
    "Idea: Stew": ItemData(1, True),
    "Idea: Stick": ItemData(1, True),
    "Idea: Stove": ItemData(1, True),
    "Idea: Sushi": ItemData(1, True),
    "Idea: Sushi": ItemData(1, True),
    "Idea: Sword": ItemData(1, True),
    "Idea: Tamago Sushi": ItemData(1, True),
    "Idea: Temple": ItemData(1, True),
    "Idea: Throwing Stars": ItemData(1, True),
    "Idea: University": ItemData(1, True),
    "Idea: Warehouse": ItemData(1, True),
    "Idea: Wishing Well": ItemData(1, True),
    "Idea: Wizard Robe": ItemData(1, True),
    "Idea: Wooden Shield": ItemData(1, True),
}

item_frequencies = {
    "Coin": 50
}

lookup_id_to_name: Dict[int, str] = {
    data.code: item_name for item_name, data in item_table.items() if data.code}
